### ISSUE TITLE
sender stream address and port had changed

### ISSUE THREAD

**Issue by DaveHu-TVU** [NVIDIA/nvnmos#5]
Hi, I use the libnvnmos to register a device to easy-nmos and found the video address and port had changed.

this is my test step:
1: 
 NvNmosSenderConfig sinkConfig[2] = { 0 };
    sinkConfig[0].sdp   = strSendVSdp.c_str();
    sinkConfig[1].sdp   = strSendASdp.c_str();
    nodeConfig.senders  = &sinkConfig[0];
    nodeConfig.num_senders = 2;
 printf("sink-0:%s\n", sinkConfig[0].sdp);
 printf("sink-1:%s\n", sinkConfig[1].sdp);
2: 
 create_nmos_node_server
remove_nmos_sender_from_node_server
add_nmos_sender_to_node_server

3: found the sdp file video address and port had changed.

the source sink0 is:
v=0
o=- 955731720 0 IN IP4 192.168.1.215
s=TVU_88DC/Video
t=0 0
a=sendonly
a=x-nvnmos-id:sink-0
a=x-nvnmos-group-hint:rx-0:video
m=video 6000 RTP/AVP 96
c=IN IP4 224.1.1.9/64
a=source-filter: incl IN IP4 224.1.1.9 192.168.1.215
a=rtpmap:96 raw/90000
a=fmtp:96 sampling=YCbCr-4:2:2; width=1920; height=1080; exactframerate=60; depth=10; TCS=SDR; colorimetry=BT709; PM=2110GPM; SSN=ST2110-20:2017; TP=2110TPN
a=ts-refclk:localmac=40-a3-6b-a0-2b-d2
a=mediaclk:direct=0
a=x-nvnmos-iface-ip:192.168.1.215
a=x-nvnmos-src-port:6000

and the transport file on NMOS serever is 
v=0
o=- 955731720 3941682372 IN IP4 192.168.1.215
s=TVU_88DC/Video
t=0 0
m=video 5004 RTP/AVP 96
c=IN IP4 232.60.245.64/64
a=ts-refclk:localmac=B8-3F-D2-43-50-38
a=mediaclk:direct=0
a=source-filter: incl IN IP4 232.60.245.64 192.168.1.215
a=rtpmap:96 raw/90000
a=fmtp:96 sampling=YCbCr-4:2:2; width=1920; height=1080; exactframerate=60; depth=10; TCS=SDR; colorimetry=BT709; PM=2110GPM; SSN=ST2110-20:2017; TP=2110TPN

**Comment by DaveHu-TVU** [comment]
![Image](https://github.com/user-attachments/assets/cdcd0c0f-fd91-4d59-9d3f-5dda74bc9b37)
![Image](https://github.com/user-attachments/assets/c98dbc57-d2ae-4a63-b3e3-91802a284cb4)

**Comment by garethsb** [comment]
That's currently intentional behaviour. The SDP file in the `NvNmosSenderConfig` is used to configure the format and other attributes of the NMOS Sender, Flow and Source, but not the initial/default transport parameters such as destination IP address and port. (These may be overridden at any time by an NMOS Controller anyway.) My thinking was that automatically assigning a [repeatable "random" address in the source-specific multicast range](https://github.com/NVIDIA/nvnmos/blob/a2d59e027cece894203cc6efe49140cfbaed5f75/src/nvnmos_impl.cpp#L1195) helped avoid issues related to multiple senders all being configured with the same address (e.g. by launching multiple instances of the same app with a hard-coded SDP file).

If you do want to set the initial values, simply call `nmos_connection_rtp_activate` with the same SDP file.

**Comment by DaveHu-TVU** [comment]
Thanks!, it works well after I add nmos_connection_rtp_activate

**Comment by garethsb** [comment]
You're welcome. Coincidentally, yesterday I published a little article on choosing initial values for the parameters in the Connection API - [NMOS Node Startup](https://www.linkedin.com/pulse/nmos-node-startup-gareth-sylvester-bradley-nbctc/).

**Comment by DaveHu-TVU** [comment]
Thanks, I will read it.
