### ISSUE TITLE
NMOS client video receiver can't find the BM IP Card sender

### ISSUE THREAD

**Issue by DaveHu-TVU** [NVIDIA/nvnmos#7]
Hi all,  
    I use libnvnmos to register a node to NMOS Server successfully, and now I want connect BM IP Card(video sender) to Nvidia ConnectX-6 card(video receiver), but NMOS Server can't list BM IP sender device, do you know why? and how can I debug it?
![Image](https://github.com/user-attachments/assets/a94b3301-c05b-4ef2-b4d0-774ea26f0036)
![Image](https://github.com/user-attachments/assets/8bfd1018-77e9-482d-8d37-ac75002a4fb9)

**Comment by DaveHu-TVU** [comment]
I'm very sorry, this might have been an issue with the NMOS Server filter conditions, I changed the filter conditions and it now shows up.

![Image](https://github.com/user-attachments/assets/01002747-ca50-4463-9fa7-cf194b01283d)

**Comment by garethsb** [comment]
Hi, @DaveHu-TVU. In the *Receiver > Connect* tab, by default the NMOS Registry UI shows only those Senders that match transport and format constraints of the Receiver. For an RTP receiver like the one you've built with nvnmos, the UI should be clever enough to match RTP Multicast-only senders like the BM IP sender shown in your final screenshot, so I suspect that there are actual format differences (e.g. different resolution or frame rate) between the configuration of the BM sender and the nvnmos receiver. In this case, disabling Constraint Sets matching will mean the UI will let you _attempt_ to connect it, but it won't work, because the nvnmos receiver will reject the connection anyway.

**Comment by DaveHu-TVU** [comment]
Thanks for your help.
I have another question:
If I need run 2 nvnmos client to register (2 senders and 2 receivers) x 2, how can I run demo?
in fact, I want know how to set the "host_name"? two example use the same host_name like "nmos-api.local"?

**Comment by garethsb** [comment]
If they're running on the same host, then they will need to run on different ports, because the NMOS Node API must have URL path _/x-nmos/node/_.

They will also need different `seed` values to ensure they generate different NMOS resource identifiers.

The nvnmos-example app constructs the seed by combining the `host_name` and `port` (see [main.c](https://github.com/NVIDIA/nvnmos/blob/a2d59e027cece894203cc6efe49140cfbaed5f75/src/main.c#L231)), so running two instances of it as follows works fine:

```sh
./nvnmos-example nmos-api.local 8080 192.0.2.0
```
```sh
./nvnmos-example nmos-api.local 8081 192.0.2.0
```

You can also give them unique host names, but they'd still need unique ports if they're actually running on the same host.

**Comment by DaveHu-TVU** [comment]
Thanks！ I think it can work now.

I have two nvnmos clients, and register two video devices: TVU_88DC_0(sender) and TVU_88DC_1(receiver)
1: video sender sdp file(sdp file 1):
```
v=0
o=- 1733112148 0 IN IP4 192.168.1.215
s=TVU_88DC_0/Video
t=0 0
a=sendonly
a=x-nvnmos-id:sink0-0
a=x-nvnmos-group-hint:rx0-0:video
m=video 6000 RTP/AVP 96
c=IN IP4 224.1.1.9/64
a=source-filter: incl IN IP4 224.1.1.9 192.168.1.215
a=rtpmap:96 raw/90000
a=fmtp:96 sampling=YCbCr-4:2:2; width=1920; height=1080; exactframerate=59.94; depth=10; TCS=SDR; colorimetry=BT709; PM=2110GPM; SSN=ST2110-20:2017; TP=2110TPN
a=ts-refclk:localmac=40-a3-6b-a0-2b-d2
a=mediaclk:direct=0
```

2: video receiver sdp file(sdp file 2):
```
v=0
o=- 955731720 0 IN IP4 192.168.1.216
s=TVU_88DC_1/Video
t=0 0
a=x-nvnmos-id:source1-0
a=x-nvnmos-group-hint:rx1-0:video
m=video 6000 RTP/AVP 96
c=IN IP4 224.1.1.11/64
a=source-filter: incl IN IP4 224.1.1.11 192.168.1.216
a=rtpmap:96 raw/90000
a=fmtp:96 sampling=YCbCr-4:2:2; width=1920; height=1080; exactframerate=59.94; depth=10; TCS=SDR; colorimetry=BT709; PM=2110GPM; SSN=ST2110-20:2017; TP=2110TPN
a=mediaclk:direct=0
a=x-nvnmos-iface-ip:192.168.1.216
```

if I connect TVU_88DC_1 to TVU_88DC_0 via NMOS Server, I can get the new sdp file(sdp file 3) from `nmos_connection_rtp_activation_callback`
as follow:
```
v=0
o=- 1733112148 3942179658 IN IP4 192.168.1.216
s=TVU_88DC_0/Video
t=0 0
a=x-nvnmos-id:source1-0
a=x-nvnmos-group-hint:rx1-0:video
6000 RTP/AVP 96
c=IN IP4 224.1.1.9/64
a=ts-refclk:localmac=B8-3F-D2-43-50-38
a=mediaclk:direct=0
a=source-filter: incl IN IP4 224.1.1.9 192.168.1.215
a=rtpmap:96 raw/90000
a=fmtp:96 sampling=YCbCr-4:2:2; width=1920; height=1080; exactframerate=59.94; depth=10; TCS=SDR; colorimetry=BT709; PM=2110GPM; SSN=ST2110-20:2017; TP=2110TPN
a=x-nvnmos-iface-ip:192.168.1.216
```

Then I can use the parameters of the sdp file3 (address and port of the 2110, parameters of the video, etc.) on the TVU_88DC_1 side to receive the video from the TVU_88DC_0 right?
Thanks again!
